#CamScanner
[Script]
Camscanner = requires-body=1,script-path=https://raw.githubusercontent.com/hoanganh732/CONFIG_BY_HOANGANH/refs/heads/main/CamScanner/CamScanner.js,type=http-response,pattern= https:\/\/(api|api-cs.*)\.intsig\.net\/purchase\/cs\/query_property\?
[MITM]
hostname = ap*.intsig.net
#************************************#
